title: My first Just the Docs Site
description: Testing the starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://Phu2.github.io/test-just-the-docs

aux_links:
  Template Repository: https://github.com/Phu2/test-just-the-docs
